# Generated by Django 4.2.13 on 2024-06-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='inside.jpg', upload_to='service')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('option', models.CharField(max_length=50)),
                ('counted_viwe', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(to='services.category')),
            ],
        ),
    ]
