# Generated by Django 4.2.13 on 2024-06-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(default='inside.jpeg', upload_to='service'),
        ),
    ]
