# Generated by Django 4.2.13 on 2024-06-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
